-   id: after_black
    name: Identify possible formatting issues caused by Black
    description: This hook looks for possible formatting issues caused by Black.
    entry: after_black
    language: python
    types: [python]
    stages: [commit, push, manual]